### ISSUE TITLE
bug和新功能请求

### ISSUE THREAD

**Issue by QianFuv** [MonianHello/JSON-i18n#1]
1. 自动保存布局无法保存浏览模式和搜索栏中的列宽
2. unicode保存似乎失效（无法保存为unicode编码，不过这个失效也无伤大雅）
3. 文件管理新增右键管理（删除文件、新建zh_cn.json文件->复制并重命名就行和右键使用资源管理器打开）
4. 现在的右键菜单还是英文！（恼

**Comment by MonianHello** [comment]
1. 因技术性原因，模型内部的列宽无法保存，可以通过快速点击列与列之间的缝隙自动匹配列宽
2. 程序中Unicode编码仅编码非ASCII字符
3. 在1.0.6版本上线
4. 以下是右键菜单中的部分英文翻译：

- Undo : 撤销
- Redo : 重做
- Cut : 剪切
- Copy : 复制
- Paste : 粘贴
- Delete : 删除
- Select All : 全选

   希望能帮到你 : )

**Comment by MonianHello** [comment]
已发布v1.0.6
